name: cbor
description: A CBOR library for Dart. An RFC8949 compliant encoding/decoding CBOR implementation.
version: 6.2.0
repository: https://github.com/shamblett/cbor
homepage: https://github.com/shamblett/cbor

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: "^1.17.2"
  typed_data: "^1.3.2"
  hex: '^0.2.0'
  convert: "^3.0.1"
  ieee754: "^1.0.3"
  meta: "^1.9.1"

dev_dependencies:
  test: "^1.24.2"
  lints: '^2.1.0'
