name: cbor
description: A CBOR library for Dart. An RFC7049 compliant encoding/decoding CBOR implementation.
version: 2.1.0
homepage: https://github.com/shamblett/cbor

environment:
 sdk: '>=2.6.0 <3.0.0'

dependencies:
 typed_data: '^1.1.6'
 convert: '^2.1.1'

dev_dependencies:
 test: '^1.11.0'
 pedantic: '^1.9.0'
 pana: '^0.13.4'
 build_runner: '^1.7.3'
 build_test: '^0.10.12'
 build_web_compilers: '^2.8.0'

