name: cbor
description: A CBOR library for Dart. An RFC8949 compliant encoding/decoding CBOR implementation.
version: 6.3.7
repository: https://github.com/shamblett/cbor
homepage: https://github.com/shamblett/cbor

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  collection: '^1.17.2'
  typed_data: '^1.3.2'
  hex: '^0.2.0'
  convert: '^3.1.2'
  ieee754: '^1.0.3'
  meta: '^1.9.1'
  characters: '^1.4.0'

dev_dependencies:
  test: '^1.28.0'
  lints: '^6.0.0'